##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## make an executable
##

all:
	@make -sC Foxely

.PHONY: clean
clean:
	@make clean -sC Foxely

.PHONY: fclean
fclean: clean
	@make fclean -sC Foxely

.PHONY: re
re: fclean all
